#!/bin/sh
#
# @name Gazebo x500
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 0
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 0

param set-default SYS_HAS_GPS 0
param set-default SYS_HAS_MAG 0

param set-default EKF2_HGT_REF 3
param set-default EKF2_GPS_CTRL 0
param set-default EKF2_MAG_TYPE 5
param set-default EKF2_EV_CTRL 11

# 重力ベクトル融合 (bit 2) を有効にする。既定の 3 (ジャイロ/加速度バイアス推定のみ)
# だと、火星重力 (3.721 m/s^2) では傾き誤差が生む速度ドリフトが地球の 1/2.64 に
# なり、静止時のゼロ速度更新だけでは EKF2 の傾き分散が 3 度まで下がらない。
# 実測: 3 のままだと arm 可能になるまで約 100 秒かかる (7 なら数秒)。
param set-default EKF2_IMU_CTRL 7

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.17
param set-default CA_ROTOR0_PY 0.17
param set-default CA_ROTOR0_KM  0.05

param set-default CA_ROTOR1_PX -0.17
param set-default CA_ROTOR1_PY -0.17
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX 0.17
param set-default CA_ROTOR2_PY -0.17
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.17
param set-default CA_ROTOR3_PY 0.17
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

param set-default MPC_THR_HOVER 0.60
